NAVBAR = "[B]ack     [H]ome"
NAVBAR2 = "[B]ack     [S]ave     [H]ome"
NAVBAR3 = "[Q]uit"
PLANE1 = "De Havilland Canada DHC-8-200"
PLANE2 = "De Havilland Canada DHC-8-400"
PLANE3 = "Fokker 100"
PLANE4 = "Bombardier CRJ700"
PLANE5 = "Sukhoi Superjet 100"
EQUALS = "="
DASH = "-"
ISYMBOL = "I"